# Change these first
owner: blacky1707 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: WSMM
    url: https://www.wsmm.de
  - name: Auktionshaus am See
    url: https://www.auktionshausamsee.de
  - name: Bilali Motoreninstandsetzung
    url: https://www.bilali-motoreninstandsetzung.de
  - name: Finanzberatung Timo Strangfeld
    url: https://www.finanzberatung-bw.de
  - name: Hannah Crasser
    url: https://www.kosmetik-ostfildern.de
  - name: Zahnärzte Krauss
    url: https://www.zahnaerzte-krauss.de
  - name: Parfümerie Albrecht
    url: https://www.pal1732.de
  - name: WSMM Bitbucket
    url: https://scm.wsmm.de
  - name: WSMM Jira
    url: https://bugs.wsmm.de
  - name: WSMM CI
    url: https://ci.wsmm.de
    
status-website: 
  theme: light
  baseUrl: /uptime
  name: WSMM Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "*/15 * * * *"
  responseTime: "* */15 * * *"
  staticSite: "*/15 * * * *"
  summary: "*/15 * * * *"
  updateTemplate: "0 * * * *"
  updates: "0 3 * * *"
  uptime: "* * * * *"
