# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: WSMM
    url: https://www.wsmm.de
  - name: Auktionshaus am See
    url: https://www.auktionshausamsee.de
  - name: Bilali Motoreninstandsetzung
    url: https://www.bilali-motoreninstandsetzung.de
    
status-website: 
  theme: light
  baseUrl: /uptime
  name: WSMM Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
